# server:
#   port: 80

# logging:
#   level:
#     root: WARN
#     be.vlaanderen.informatievlaanderen.ldes.ldio.Application: INFO

orchestrator:
  pipelines:
    - name: metingen-pipeline-raw
      description: "Aquafin metingen JSON message (raw) in using HTTP, OSLO transformation, version creation & HTTP sending."
      input:
        name: Ldio:HttpIn
        adapter:
          name: Ldio:JsonToLdAdapter
          config:
            context: |
              {
                "@context": {
                  "@vocab": "https://aquafin.be/ns#"
                }
              }
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: |
              CONSTRUCT {
                GRAPH ?uriGemetenAfstand {
                  ?uriGemetenAfstand ?p ?o .
                }
                GRAPH ?uriTemperatuur {
                  ?uriTemperatuur ?p ?o .
                }
                GRAPH ?uriDebiet {
                  ?uriDebiet ?p ?o .
                }
              }
              WHERE { 
                ?s ?p ?o .

                BIND (uri("https://aquafin.be/id/observatie/001/gemetenAfstand/2024-07-29T15:00:00Z") as ?uriGemetenAfstand)
                BIND (uri("https://aquafin.be/id/observatie/001/temperatuur/2024-07-29T15:00:00Z") as ?uriTemperatuur)
                BIND (uri("https://aquafin.be/id/observatie/001/debiet/2024-07-29T15:00:00Z") as ?uriDebiet)
              }
      outputs:
        - name: Ldio:ConsoleOut